[program:laravel-horizon]
process_name=%(program_name)s
command=php /var/www/artisan horizon
directory=/var/www

autostart=true
autorestart=true
stopasgroup=true
killasgroup=true

numprocs=1

redirect_stderr=true
stdout_logfile=/var/www/storage/logs/horizon.log
stopwaitsecs=3600